#!/bin/sh
MQTTBROKER=tcp://DanielPi3:1883
NETWORK=192.168.2.0/24
BROADCASTPERIOD=10
LOGDIR=.
DEBUGRUNLENGTH=600
rm -f $LOGDIR/HomeAutomationLog
export MQTTBROKER NETWORK LOGDIR BROADCASTPERIOD DEBUGRUNLENGTH
./kasaplug -d
